#!/usr/bin/env python
# coding: utf-8

# In[2]:


#initialize
try:
    file = open('record.txt', 'r')
except FileNotFoundError:
    print("hello")


# In[23]:


#install file
def install_file(file_name):
    list_ = []
    f = open('file_name', 'r', encoding = 'utf-8')
    for i in f.readlines():
        list_ += [i]
    
    for i in list_:
        tmp = i.split("\xa0")
        print(tmp)

    


# In[ ]:


#practice
def practice(list_):


# In[ ]:


#close program
def close_program()


# In[ ]:


#main
while True:
    command = input("enter your command:")
    if command == "install":
        file_name = input("enter file name:")
        install_file(file_name)
    elif command == "practice":
        list_practice = input("enter which score you want to practice:")
        practice(list_practice)
    elif command == "close":
        close_program()
        break
        
print("byebye")

